### ISSUE TITLE
limited set of responses from bot

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot-old#2]
## Expected Behavior
asking sub-question regarding type of disaster to report by user

## Actual Behavior
asking how can I help you a second time

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:Windows 8 Professional - 64bit
  - Platform:REACH

![capture](https://user-images.githubusercontent.com/25951555/33362256-83df296c-d516-11e7-86d7-03bae9c420b2.PNG)

**Comment by matthewberryman** [comment]
Let's keep track of this one as we work on https://github.com/MSFREACH/msf-reach-chatbot/issues/5

**Comment by LucieGueuning** [comment]
PS, the twitter duplication is not happening all the time, just occasionally. I will let you know when that’s fixed,

**Comment by matthewberryman** [comment]
This issue is in terms of the set of possible responses from the bot, i.e. you may get its default responses multiple times in response to different questions:
<img width="256" alt="screenshot 2018-01-22 08 35 34" src="https://user-images.githubusercontent.com/2288238/35199212-521c7f2a-ff4f-11e7-96a0-cac3e7d4f986.png">,
which should get better as we work on #5 but some other tweaks to the code may be necessary.

This issue is is different to the twitter duplication issue #12 (and I haven't seen any cases in our testing since I did deploy the fixed code), where one question would see the same response being sent twice
<img width="607" alt="screenshot 2018-01-22 08 33 37" src="https://user-images.githubusercontent.com/2288238/35199222-74017924-ff4f-11e7-96a0-d336410815cf.png">
