### ISSUE TITLE
define core vocabulary

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-chatbot-old#5]
The chatbot needs to be programmed with a core set of keywords, and the steps for doing this and updating the list need to be documented (#4)

**Comment by matthewberryman** [comment]
https://docs.google.com/spreadsheets/d/1p76HmfaQu82Ma-oxmlxO91_vD4JQgwz4DJ4Xat7E77U/edit?usp=sharing

**Comment by LucieGueuning** [comment]
'generic reports' and get the chatbot taking the key phrase list and response for that

**Comment by matthewberryman** [comment]
It's not clear to me what you're saying. If we want to support reports not linked to existing events (@anexact any updates from ethnography) then in in the google doc we need the keywords defined that will trigger the bot to send a generic message + reporting link.

**Comment by matthewberryman** [comment]
@LucieGueuning I've just updated the google doc with the vocabulary as it stands now

**Comment by matthewberryman** [comment]
@anexact can you please have a look at this language first, and also think about UX for chatbot (incl. report and contact cards https://github.com/MSFREACH/msf-reach/issues/194 )

**Comment by LucieGueuning** [comment]
Just noting that we still need to work on a couple of key issues namely defining the core language to make it smart, and automating addition of new events.

**Comment by LucieGueuning** [comment]
Some thoughts and progress on twitter search:

I think the best search search terms to use are:
Type or subtype (but not both)
Country*
Possibly the year?

* Here I mean as a keyword not as a location (bounding box) filter which will not work reliably because of Twitter UX issues.

I have some changes in the dev environment just going live now (after local testing) to geocode location of the event on the map to country, and include that in the metadata, used in Twitter search as per above. Important notes:
•	This only applies on creation of new events. I need to separately work on code for updated events, and old events already in the system.
•	I am using Google geocoding with an API key I have, so do not put any sensitive location information into the dev environment until we’ve had a discussion around privacy issues and also the amount we want to put through (there’s a fairly generous free limit but still…)
•	There is still some UI work to display the country information elsewhere in the system

This test event in the dev environment, local to me, had Australia automatically added as the country, and that shows a fairly decent twitter search results by default:
https://dev.msf-reach.org/events/?eventId=32

**Comment by matthewberryman** [comment]
@LucieGueuning just noting I have put some comments in the google sheet document.
